apiVersion: v1
kind: Service
metadata:
  name: springbootapp
spec:
  type: NodePort  # or LoadBalancer if on cloud
  selector:
    app: springbootapp
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30080  # Optional: Choose a node port (range 30000–32767)
